name: safarirally2023
description: Safari Rally 2023 Environmental Sustainability Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  provider:
  cloud_firestore:
  flutter_easyloading:
  email_validator:
  geocoding:
  image_picker:
  location:
  geolocator:
  persistent_bottom_nav_bar:
  flutter_timer_countdown:
  cached_network_image:
  table_calendar:
  google_maps_flutter:
  flutter_spinkit: ^5.1.0
  multi_select_flutter: ^4.1.3
  group_button: ^5.2.2
  survey_kit: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf